

import { Category, MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'm1',
    name: '招牌炒泡麵',
    name_en: 'Signature Fried Noodles',
    price: 55,
    category: Category.FOOD,
    description: '香氣四溢的經典炒泡麵，加入秘製醬汁與蔬菜。',
    description_en: 'Classic fried instant noodles with secret sauce and vegetables.',
    options: [
      { id: 'opt-cheese', name: '加起司', name_en: 'Add Cheese', price: 10 },
      { id: 'opt-egg', name: '加蛋', name_en: 'Add Egg', price: 10, note: '本來就有附一個', note_en: 'One is already included' },
    ]
  },
  {
    id: 'm2',
    name: '爆汁香腸',
    name_en: 'Grilled Sausage',
    price: 45,
    category: Category.FOOD,
    description: '外酥內嫩，咬下去會爆汁的炭烤香腸。',
    description_en: 'Crispy on the outside, juicy on the inside charcoal grilled sausage.',
  },
  {
    id: 'm4',
    name: '棉花糖串',
    name_en: 'Marshmallow Skewer',
    price: 15,
    category: Category.FOOD,
    description: '口感綿密，香甜可口的棉花糖串。',
    description_en: 'Soft and sweet marshmallow skewer.',
    options: [
      { id: 'opt-condensed-milk', name: '加煉乳', name_en: 'Add Condensed Milk', price: 5 },
      { id: 'opt-chocolate-sauce', name: '加巧克力醬', name_en: 'Add Chocolate Sauce', price: 5 },
    ]
  },
  {
    id: 'd1',
    name: '古早味紅茶',
    name_en: 'Classic Black Tea',
    price: 30,
    category: Category.DRINK,
    description: '清涼解渴，甜而不膩的傳統紅茶。',
    description_en: 'Refreshing and not too sweet traditional black tea.',
  },
  {
    id: 'd2',
    name: '可樂',
    name_en: 'Coke',
    price: 20,
    category: Category.DRINK,
    description: '經典碳酸飲料，暢快過癮。',
    description_en: 'Classic carbonated soft drink.',
  },
  {
    id: 'd3',
    name: '雪碧',
    name_en: 'Sprite',
    price: 20,
    category: Category.DRINK,
    description: '清爽檸檬萊姆風味汽水。',
    description_en: 'Refreshing lemon-lime soda.',
  },
];

export const STORAGE_KEY = 'fairday_orders_v1';
export const CUSTOMER_STORAGE_KEY = 'fairday_customer_history_v1'; // Separate key for customer
export const COUNTER_KEY = 'fairday_order_counter_v1';
// Fixed ID for automatic connection - updated to v3 to avoid conflicts
export const FIXED_KITCHEN_ID = 'fairday-kitchen-v3';

// Kitchen Password HASH (SHA-256)
// 為了安全，我們不儲存明碼。
// 預設密碼 '980415' 的 Hash 如下。
// 若要更換密碼，請在登入畫面輸入新密碼，按登入，然後看 F12 Console，系統會顯示新密碼的 Hash，請複製並貼上到這裡。
export const KITCHEN_PASSWORD_HASH = '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4';

export const TRANSLATIONS = {
  'zh-Hant': {
    app: {
      title: '無法顯示攤位名稱',
      subtitle: '園遊會智慧點餐系統',
      customerBtn: '我是客人 (點餐模式)',
      kitchenBtn: '我是廚房 (後台模式)',
      queueBtn: '叫號顯示 (叫號模式)',
      footer: '適用於手機、平板與電腦',
    },
    common: {
      loading: '載入中...',
      back: '退出',
      confirm: '確認',
      cancel: '取消',
      save: '儲存變更',
      delete: '刪除',
      close: '關閉',
      edit: '編輯',
      quantity: '數量',
      unit: '份',
      warning: '警告',
      password: '密碼',
      login: '登入後台',
      accessDenied: '密碼錯誤',
      enterPassword: '請輸入管理密碼',
    },
    customer: {
      stallName: '無法顯示攤位名稱',
      stallName_en: 'FairDay Eats', // Fallback
      connectTitle: '連線至廚房',
      connectDesc: '正在自動連線至攤位主機...',
      connectPlaceholder: '輸入 4 位數代碼',
      connectBtn: '連線',
      skipBtn: '略過 (僅本機測試)',
      connected: '已連線',
      disconnected: '未連線',
      reconnecting: '正在搜尋廚房主機...',
      soldOut: '已售完',
      addToOrder: '加入點單',
      restocking: '補貨中',
      stock: '剩餘庫存',
      addOns: '加購選項',
      note: '備註 (選填)',
      notePlaceholder: '例如：少冰、不要蔥...',
      addToCart: '確認加入',
      addedToCart: '確認加入購物車',
      viewOrder: '查看訂單',
      yourOrder: '您的訂單',
      total: '總金額',
      submitOrder: '確認送出訂單',
      processing: '處理中...',
      orderSuccess: '點餐成功！',
      orderNumber: '您的取餐號碼',
      payInstruction: '請先至櫃檯',
      payInstructionBold: '付款',
      payInstructionEnd: '，付款後將開始製作餐點。',
      backToHome: '返回首頁',
      inventoryLow: '抱歉，庫存不足！',
      useLocalConfirm: '目前未連線至廚房，將使用本機號碼牌。\n注意：可能與其他裝置重複。是否繼續？',
      checkQueue: '查看叫號',
      currentServing: '目前叫號',
      noActiveQueue: '尚無叫號',
      limitReached: '已達上限',
    },
    kitchen: {
      title: '後廚管理系統',
      connectionActive: '系統連線正常',
      connectionLost: '連線中斷/重試中...',
      tabletCode: '平板連線代碼',
      testSound: '測試音效',
      inventory: '庫存管理',
      reports: '營收報表',
      resetCounter: '重置號碼',
      clearHistory: '清除紀錄',
      unpaid: '未付款',
      preparing: '製作中',
      completed: '已完成',
      pickedUp: '已取餐',
      cancelled: '已取消',
      markPaid: '確認已付款',
      completeOrder: '完成訂單',
      editOrder: '修改訂單內容',
      addItem: '加點其他品項',
      selectItem: '選擇餐點...',
      toppings: '配料選擇',
      newTotal: '新總金額',
      revenueCenter: '營收報表中心',
      overview: '營收概況',
      history: '歷史訂單明細',
      systemRevenue: '系統營收',
      adjustment: '手動調整',
      finalTotal: '最終總營收',
      totalOrders: '訂單總數',
      productSales: '商品銷售排行 (進銷存)',
      addOnUsage: '加購選項消耗 (食材庫存)',
      itemName: '品項名稱',
      currentStock: '目前庫存',
      action: '操作',
      resetAll50: '全部重設為 50',
      soldOut: '售完',
      noOrders: '尚無訂單',
      confirmResetTitle: '確定要重置號碼嗎？',
      confirmResetMsg: '這將重置每日計數器。注意：若系統中仍有未清除的訂單，新號碼將會接續目前最大的號碼，以避免重複。若要從 #1 開始，請先清除紀錄。',
      confirmClearTitle: '確定要清除紀錄嗎？',
      confirmClearMsg: '這將永久刪除所有「已完成」、「已取餐」及「已取消」的訂單資料。此操作無法復原。',
      confirmAction: '確認執行',
      resetSuccess: '號碼已重置',
    },
    queue: {
      connectHost: '連線至廚房主機',
      connectDesc: '系統將自動連線並啟用音效',
      startDisplay: '開始顯示',
      localMode: '僅使用本機資料',
      preparing: '餐點準備中',
      ready: '請取餐',
      nowServing: '現正叫號',
      lastCalled: '歷史叫號',
      waiting: '等待叫號中...',
      synced: '已連線同步',
    }
  },
  'en': {
    app: {
      title: 'Stall Name Unavailable',
      subtitle: 'Smart Fair POS System',
      customerBtn: 'Customer (Order)',
      kitchenBtn: 'Kitchen (Admin)',
      queueBtn: 'Queue (Display)',
      footer: 'Designed for Mobile, Tablet & Desktop',
    },
    common: {
      loading: 'Loading...',
      back: 'Exit',
      confirm: 'Confirm',
      cancel: 'Cancel',
      save: 'Save Changes',
      delete: 'Delete',
      close: 'Close',
      edit: 'Edit',
      quantity: 'Qty',
      unit: '',
      warning: 'Warning',
      password: 'Password',
      login: 'Login',
      accessDenied: 'Incorrect Password',
      enterPassword: 'Enter Admin Password',
    },
    customer: {
      stallName: 'Stall Name Unavailable',
      stallName_en: 'FairDay Eats',
      connectTitle: 'Connect to Kitchen',
      connectDesc: 'Connecting to stall system automatically...',
      connectPlaceholder: '4-Digit Code',
      connectBtn: 'Connect',
      skipBtn: 'Skip (Local Test Only)',
      connected: 'Connected',
      disconnected: 'Offline',
      reconnecting: 'Searching for Kitchen...',
      soldOut: 'SOLD OUT',
      addToOrder: 'Add to Order',
      restocking: 'Restocking',
      stock: 'Stock',
      addOns: 'Add-ons',
      note: 'Note (Optional)',
      notePlaceholder: 'e.g. No ice, less spicy...',
      addToCart: 'Add to Cart',
      addedToCart: 'Added to Cart',
      viewOrder: 'View Order',
      yourOrder: 'Your Order',
      total: 'Total',
      submitOrder: 'Place Order',
      processing: 'Processing...',
      orderSuccess: 'Order Placed!',
      orderNumber: 'Your Order Number',
      payInstruction: 'Please pay at the counter to',
      payInstructionBold: 'confirm',
      payInstructionEnd: ' your order.',
      backToHome: 'Back to Home',
      inventoryLow: 'Sorry, insufficient stock!',
      useLocalConfirm: 'Not connected to kitchen. Use local order number? (May duplicate)',
      checkQueue: 'Check Queue',
      currentServing: 'Now Serving',
      noActiveQueue: 'Waiting...',
      limitReached: 'Limit Reached',
    },
    kitchen: {
      title: 'Kitchen System',
      connectionActive: 'System Online',
      connectionLost: 'Connection Lost / Retrying...',
      tabletCode: 'Tablet Code',
      testSound: 'Test Sound',
      inventory: 'Inventory',
      reports: 'Revenue',
      resetCounter: 'Reset Counter',
      clearHistory: 'Clear History',
      unpaid: 'Unpaid',
      preparing: 'Preparing',
      completed: 'Completed',
      pickedUp: 'Picked Up',
      cancelled: 'Cancelled',
      markPaid: 'Mark Paid',
      completeOrder: 'Complete',
      editOrder: 'Edit Order',
      addItem: 'Add Item',
      selectItem: 'Select Item...',
      toppings: 'Toppings',
      newTotal: 'New Total',
      revenueCenter: 'Revenue Center',
      overview: 'Overview',
      history: 'History',
      systemRevenue: 'System Revenue',
      adjustment: 'Adjustment',
      finalTotal: 'Final Total',
      totalOrders: 'Total Orders',
      productSales: 'Product Sales',
      addOnUsage: 'Add-on Usage',
      itemName: 'Item Name',
      currentStock: 'Stock',
      action: 'Action',
      resetAll50: 'Reset All to 50',
      soldOut: 'Sold Out',
      noOrders: 'No Orders',
      confirmResetTitle: 'Reset Order Counter?',
      confirmResetMsg: 'This will reset the daily counter. Note: If there are existing orders, new numbers will continue from the highest one to avoid duplicates. Clear history first to start from #1.',
      confirmClearTitle: 'Clear History?',
      confirmClearMsg: 'This will permanently delete all Completed, Picked Up, and Cancelled orders. This action cannot be undone.',
      confirmAction: 'Confirm Action',
      resetSuccess: 'Counter Reset',
    },
    queue: {
      connectHost: 'Connect to Kitchen',
      connectDesc: 'System connects automatically with sound enabled',
      startDisplay: 'Start Display',
      localMode: 'Local Mode Only',
      preparing: 'Preparing',
      ready: 'Ready',
      nowServing: 'Now Serving',
      lastCalled: 'History',
      waiting: 'Waiting...',
      synced: 'Synced',
    }
  }
};