import type { Category, MenuItem } from '@/types'

// === 翻譯 ===

export type Translations = { [K in keyof typeof translations.zh]: string }

export const translations = {
  zh: {
    // 通用
    appName: '宏麵屋',
    confirm: '確認',
    cancel: '取消',
    save: '儲存',
    delete: '刪除',
    edit: '編輯',
    add: '新增',
    back: '返回',
    close: '關閉',
    reset: '重設',
    search: '搜尋',
    noData: '暫無資料',

    // 首頁
    customerOrder: '顧客點餐',
    kitchenManage: '廚房管理',
    queueDisplay: '叫號看板',
    stallName: '店舖名稱',
    language: '語言',

    // 顧客端
    menu: '菜單',
    allCategories: '全部',
    soldOut: '完売',
    addToCart: '加入購物車',
    cart: '購物車',
    cartEmpty: '購物車是空的',
    orderItems: '品項',
    total: '合計',
    submitOrder: '送出訂單',
    orderSuccess: '下單成功！',
    yourNumber: '您的號碼',
    pleasePayAt: '請至櫃台付款',
    continueShopping: '繼續點餐',
    quantity: '數量',
    notes: '備註',
    notesPlaceholder: '特殊需求（如：麵硬、湯濃、不加蔥）',
    options: '加購選項',
    itemSubtotal: '小計',
    clearCart: '清空購物車',
    confirmClearCart: '確定要清空購物車嗎？',
    confirmOrder: '確認訂單',
    orderSummary: '訂單摘要',

    // 廚房端
    kitchenLogin: '廚房登入',
    password: '密碼',
    login: '登入',
    wrongPassword: '密碼錯誤',
    logout: '登出',
    orders: '訂單',
    inventory: '庫存',
    menuEditor: '菜單編輯',
    revenue: '營收',
    unpaid: '待付款',
    preparing: '製作中',
    completed: '已完成',
    pickedUp: '已取餐',
    cancelled: '已取消',
    markPaid: '標記已付款',
    markPreparing: '開始製作',
    markCompleted: '完成製作',
    markPickedUp: '已取餐',
    markCancelled: '取消訂單',
    confirmCancel: '確定要取消這筆訂單嗎？',
    orderNumber: '訂單號碼',
    waitTime: '等候',
    minutes: '分鐘',
    newOrder: '新訂單',
    stock: '庫存',
    unlimited: '不限',
    setStock: '設定庫存',
    markSoldOut: '標記完売',
    restoreAvailable: '恢復供應',
    resetAll: '全部重設',
    confirmResetInventory: '確定要重設所有庫存嗎？',

    // 菜單編輯器
    addCategory: '新增分類',
    editCategory: '編輯分類',
    categoryName: '分類名稱',
    categoryNameEn: '分類英文名稱',
    addItem: '新增品項',
    editItem: '編輯品項',
    itemName: '品項名稱',
    itemNameEn: '品項英文名稱',
    price: '價格',
    category: '分類',
    description: '說明',
    addOption: '新增選項',
    optionName: '選項名稱',
    optionNameEn: '選項英文名稱',
    optionPrice: '選項價格',
    confirmDeleteCategory: '確定要刪除此分類？分類下的品項也會一併刪除。',
    confirmDeleteItem: '確定要刪除此品項嗎？',

    // 營收報表
    totalRevenue: '總營收',
    totalOrders: '總訂單數',
    averageOrder: '平均客單價',
    topItems: '熱門品項',
    salesQuantity: '銷量',
    salesRevenue: '營收',
    hourlyDistribution: '時段訂單分布',
    noOrders: '尚無訂單資料',
    manualAdjust: '手動調整',
    adjustAmount: '調整金額',
    adjustReason: '調整原因',

    // 叫號
    nowServing: '現在叫號',
    preparingOrders: '準備中',
    recentCompleted: '最近完成',
    noCurrentOrder: '目前無叫號',
    callAgain: '重新叫號',
    fullscreen: '全螢幕',
    exitFullscreen: '退出全螢幕',

    // 連線
    connected: '已連線',
    disconnected: '未連線',
    connecting: '連線中...',
    localMode: '本機模式',
    deviceId: '設備 ID',
    hostId: '主機 ID',
    connect: '連線',

    // 設定
    settings: '設定',
    setPassword: '設定密碼',
    newPassword: '新密碼',
    confirmPassword: '確認密碼',
    passwordMismatch: '密碼不一致',
    passwordUpdated: '密碼已更新',
    soundEnabled: '音效',
    speechEnabled: '語音播報',
    volume: '音量',
    resetData: '重設資料',
    resetOrders: '清除訂單記錄',
    resetCounter: '重設號碼計數器',
    confirmResetOrders: '確定要清除所有訂單記錄嗎？此操作無法復原。',
    confirmResetCounter: '確定要將號碼計數器歸零嗎？',
  },
  en: {
    appName: 'Hiromen-ya',
    confirm: 'Confirm',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    back: 'Back',
    close: 'Close',
    reset: 'Reset',
    search: 'Search',
    noData: 'No data',

    customerOrder: 'Order',
    kitchenManage: 'Kitchen',
    queueDisplay: 'Queue',
    stallName: 'Store Name',
    language: 'Language',

    menu: 'Menu',
    allCategories: 'All',
    soldOut: 'Sold Out',
    addToCart: 'Add to Cart',
    cart: 'Cart',
    cartEmpty: 'Cart is empty',
    orderItems: 'items',
    total: 'Total',
    submitOrder: 'Submit Order',
    orderSuccess: 'Order Placed!',
    yourNumber: 'Your Number',
    pleasePayAt: 'Please pay at the counter',
    continueShopping: 'Continue Ordering',
    quantity: 'Qty',
    notes: 'Notes',
    notesPlaceholder: 'Special requests (e.g., firm noodles, rich broth)',
    options: 'Options',
    itemSubtotal: 'Subtotal',
    clearCart: 'Clear Cart',
    confirmClearCart: 'Clear all items from cart?',
    confirmOrder: 'Confirm Order',
    orderSummary: 'Order Summary',

    kitchenLogin: 'Kitchen Login',
    password: 'Password',
    login: 'Login',
    wrongPassword: 'Wrong password',
    logout: 'Logout',
    orders: 'Orders',
    inventory: 'Inventory',
    menuEditor: 'Menu Editor',
    revenue: 'Revenue',
    unpaid: 'Unpaid',
    preparing: 'Preparing',
    completed: 'Completed',
    pickedUp: 'Picked Up',
    cancelled: 'Cancelled',
    markPaid: 'Mark Paid',
    markPreparing: 'Start Preparing',
    markCompleted: 'Mark Completed',
    markPickedUp: 'Picked Up',
    markCancelled: 'Cancel Order',
    confirmCancel: 'Cancel this order?',
    orderNumber: 'Order #',
    waitTime: 'Wait',
    minutes: 'min',
    newOrder: 'New Order',
    stock: 'Stock',
    unlimited: 'Unlimited',
    setStock: 'Set Stock',
    markSoldOut: 'Mark Sold Out',
    restoreAvailable: 'Restore',
    resetAll: 'Reset All',
    confirmResetInventory: 'Reset all inventory?',

    addCategory: 'Add Category',
    editCategory: 'Edit Category',
    categoryName: 'Category Name',
    categoryNameEn: 'Category Name (EN)',
    addItem: 'Add Item',
    editItem: 'Edit Item',
    itemName: 'Item Name',
    itemNameEn: 'Item Name (EN)',
    price: 'Price',
    category: 'Category',
    description: 'Description',
    addOption: 'Add Option',
    optionName: 'Option Name',
    optionNameEn: 'Option Name (EN)',
    optionPrice: 'Option Price',
    confirmDeleteCategory: 'Delete this category? All items in it will also be deleted.',
    confirmDeleteItem: 'Delete this item?',

    totalRevenue: 'Total Revenue',
    totalOrders: 'Total Orders',
    averageOrder: 'Avg Order Value',
    topItems: 'Top Items',
    salesQuantity: 'Qty Sold',
    salesRevenue: 'Revenue',
    hourlyDistribution: 'Hourly Orders',
    noOrders: 'No order data yet',
    manualAdjust: 'Manual Adjust',
    adjustAmount: 'Amount',
    adjustReason: 'Reason',

    nowServing: 'Now Serving',
    preparingOrders: 'Preparing',
    recentCompleted: 'Recent',
    noCurrentOrder: 'No current order',
    callAgain: 'Call Again',
    fullscreen: 'Fullscreen',
    exitFullscreen: 'Exit Fullscreen',

    connected: 'Connected',
    disconnected: 'Disconnected',
    connecting: 'Connecting...',
    localMode: 'Local Mode',
    deviceId: 'Device ID',
    hostId: 'Host ID',
    connect: 'Connect',

    settings: 'Settings',
    setPassword: 'Set Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    passwordMismatch: 'Passwords do not match',
    passwordUpdated: 'Password updated',
    soundEnabled: 'Sound',
    speechEnabled: 'Speech',
    volume: 'Volume',
    resetData: 'Reset Data',
    resetOrders: 'Clear Orders',
    resetCounter: 'Reset Counter',
    confirmResetOrders: 'Clear all order records? This cannot be undone.',
    confirmResetCounter: 'Reset the order counter to zero?',
  },
} as const

// === 預設菜單（拉麵） ===

export const defaultCategories: Category[] = [
  { id: 'cat-1', name: '拉麵', nameEn: 'Ramen', order: 0 },
  { id: 'cat-2', name: '配菜', nameEn: 'Side Dishes', order: 1 },
  { id: 'cat-3', name: '飲料', nameEn: 'Drinks', order: 2 },
  { id: 'cat-4', name: '甜點', nameEn: 'Desserts', order: 3 },
]

export const defaultMenuItems: MenuItem[] = [
  // 拉麵
  {
    id: 'item-1',
    categoryId: 'cat-1',
    name: '豚骨拉麵',
    nameEn: 'Tonkotsu Ramen',
    description: '濃郁豚骨白湯，18小時熬製',
    descriptionEn: 'Rich pork bone broth, 18-hour simmer',
    price: 180,
    options: [
      { id: 'opt-1', name: '加味玉', nameEn: 'Add Ajitama Egg', price: 30 },
      { id: 'opt-2', name: '加叉燒', nameEn: 'Add Chashu', price: 40 },
      { id: 'opt-3', name: '大盛', nameEn: 'Large Portion', price: 30 },
    ],
    available: true,
    stock: -1,
    order: 0,
  },
  {
    id: 'item-2',
    categoryId: 'cat-1',
    name: '醬油拉麵',
    nameEn: 'Shoyu Ramen',
    description: '經典醬油清湯，昆布柴魚底',
    descriptionEn: 'Classic soy sauce broth, kombu & bonito base',
    price: 160,
    options: [
      { id: 'opt-4', name: '加味玉', nameEn: 'Add Ajitama Egg', price: 30 },
      { id: 'opt-5', name: '加叉燒', nameEn: 'Add Chashu', price: 40 },
      { id: 'opt-6', name: '大盛', nameEn: 'Large Portion', price: 30 },
    ],
    available: true,
    stock: -1,
    order: 1,
  },
  {
    id: 'item-3',
    categoryId: 'cat-1',
    name: '味噌拉麵',
    nameEn: 'Miso Ramen',
    description: '北海道白味噌，奶油玉米風味',
    descriptionEn: 'Hokkaido white miso, butter corn flavor',
    price: 180,
    options: [
      { id: 'opt-7', name: '加味玉', nameEn: 'Add Ajitama Egg', price: 30 },
      { id: 'opt-8', name: '加叉燒', nameEn: 'Add Chashu', price: 40 },
      { id: 'opt-9', name: '大盛', nameEn: 'Large Portion', price: 30 },
    ],
    available: true,
    stock: -1,
    order: 2,
  },
  {
    id: 'item-4',
    categoryId: 'cat-1',
    name: '鹽味拉麵',
    nameEn: 'Shio Ramen',
    description: '清爽鹽味，雞白湯底',
    descriptionEn: 'Light salt broth, chicken base',
    price: 160,
    options: [
      { id: 'opt-10', name: '加味玉', nameEn: 'Add Ajitama Egg', price: 30 },
      { id: 'opt-11', name: '加叉燒', nameEn: 'Add Chashu', price: 40 },
    ],
    available: true,
    stock: -1,
    order: 3,
  },
  {
    id: 'item-5',
    categoryId: 'cat-1',
    name: '地獄辣味拉麵',
    nameEn: 'Hell Fire Ramen',
    description: '豚骨辣味噌，挑戰你的極限',
    descriptionEn: 'Spicy miso tonkotsu, challenge your limits',
    price: 190,
    options: [
      { id: 'opt-12', name: '加味玉', nameEn: 'Add Ajitama Egg', price: 30 },
      { id: 'opt-13', name: '加叉燒', nameEn: 'Add Chashu', price: 40 },
    ],
    available: true,
    stock: -1,
    order: 4,
  },

  // 配菜
  {
    id: 'item-6',
    categoryId: 'cat-2',
    name: '日式煎餃',
    nameEn: 'Gyoza (6pcs)',
    price: 80,
    options: [],
    available: true,
    stock: -1,
    order: 0,
  },
  {
    id: 'item-7',
    categoryId: 'cat-2',
    name: '唐揚雞',
    nameEn: 'Karaage Chicken',
    price: 90,
    options: [],
    available: true,
    stock: -1,
    order: 1,
  },
  {
    id: 'item-8',
    categoryId: 'cat-2',
    name: '毛豆',
    nameEn: 'Edamame',
    price: 50,
    options: [],
    available: true,
    stock: -1,
    order: 2,
  },
  {
    id: 'item-9',
    categoryId: 'cat-2',
    name: '明太子飯糰',
    nameEn: 'Mentaiko Onigiri',
    price: 60,
    options: [],
    available: true,
    stock: -1,
    order: 3,
  },

  // 飲料
  {
    id: 'item-10',
    categoryId: 'cat-3',
    name: '可爾必思',
    nameEn: 'Calpis',
    price: 40,
    options: [],
    available: true,
    stock: -1,
    order: 0,
  },
  {
    id: 'item-11',
    categoryId: 'cat-3',
    name: '烏龍茶',
    nameEn: 'Oolong Tea',
    price: 35,
    options: [],
    available: true,
    stock: -1,
    order: 1,
  },
  {
    id: 'item-12',
    categoryId: 'cat-3',
    name: '彈珠汽水',
    nameEn: 'Ramune Soda',
    price: 50,
    options: [],
    available: true,
    stock: -1,
    order: 2,
  },

  // 甜點
  {
    id: 'item-13',
    categoryId: 'cat-4',
    name: '抹茶冰淇淋',
    nameEn: 'Matcha Ice Cream',
    price: 60,
    options: [],
    available: true,
    stock: -1,
    order: 0,
  },
]

// === 預設密碼 (SHA-256 of "1234") ===
export const DEFAULT_PASSWORD_HASH = '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4'
